### ISSUE TITLE
Steps in "Consuming the secured RESTful APIs by JWT" doesn't work

### ISSUE THREAD

**Issue by shamjithantholi** [OpenLiberty/guide-liberty-deep-dive#129]
Steps says that we can make authorized request to the new /client/{hostname} endpoint using below given command, but in actual, its failing with error "failed to connect to localhost:9443"

curl -k --user bob:bobpwd -X POST 'https://localhost:9443/inventory/api/systems/client/localhost'

**Comment by shin19991207** [comment]
Hello @shamjithantholi 

I tried to reproduce the issue but there was no problem when accessing the new **/client/{hostname}** endpoint through port **9443**.

Can you make sure you see the following message displays on the dev mode of the **inventory** microservice console after running `mvn liberty:dev` from the **start/inventory** directory.
```
************************************************************************
*    Liberty is running in dev mode.
*        ...
*        
*    Liberty server port information:
*        Liberty server HTTP port: [ 9080 ]
*        Liberty server HTTPS port: [ 9443 ]
*        Liberty debug port: [ 7777 ]
************************************************************************
```

Also, make sure the following message displays on the **system** microservice console after running the **system** microservice from the **finish** directory.
```
CWWKF0011I: The defaultServer server is ready to run a smarter planet. ...
```

Let me know if you still have problem making request to this endpoint.

**Comment by gkwan-ibm** [comment]
hi @shamjithantholi we are closing this issue. You may reopen if you still have the problem.
