### ISSUE TITLE
Steps in "Deploying the microservice to Kubernetes" doesn't work

### ISSUE THREAD

**Issue by shamjithantholi** [OpenLiberty/guide-liberty-deep-dive#130]
the command "kubectl port-forward svc/inventory-deployment 9443" is not working, it says address already in use

**Comment by shamjithantholi** [comment]
this is my first try

**Comment by shin19991207** [comment]
Hello @shamjithantholi 

I see that you're getting a problem with **port 9443** as similar to [this issue](https://github.com/OpenLiberty/guide-liberty-deep-dive/issues/129). Please ensure that there is no process locking **port 9443** before you run this application. 

If you are using a mac, you can find the pid of the process locking **port 9443** by running the command `lsof -i:9443`. Then run `kill -9 [pid]` with the **pid** outputted from the previous command to kill the locking process.

**Comment by gkwan-ibm** [comment]
hi @shamjithantholi we are closing this issue. You may reopen it if you still have the problem after doing Morgan's [suggestion](https://github.com/OpenLiberty/guide-liberty-deep-dive/issues/130#issuecomment-1141629270).
