### ISSUE TITLE
JQ command not found

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/guide-liberty-deep-dive#152]
Would it be worth adding `JQ` to pre-reqs so that users know they have install it if they haven't already?

**Comment by gkwan-ibm** [comment]
suggest remove the `| jq` from the following at the **Securing RESTful APIs** section
```
curl -s 'http://localhost:9080/inventory/api/systems' | jq
```

Of course, the cloud-hosted version should use `jq`

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/guide-liberty-deep-dive/pull/162 - PR in progress

**Comment by jakub-pomykala** [comment]
PR ready for review [here](https://github.com/OpenLiberty/guide-liberty-deep-dive/pull/162)
