### ISSUE TITLE
Unexpected error CWWKS9660E on console

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/guide-liberty-deep-dive#234]
Seeing this error on Liberty's command window running 'mvn liberty:dev' at the end of the JPA section before setting up user registry.

```
[INFO] [ERROR   ] CWWKS9660E: The orb element with the defaultOrb id attribute requires a user registry but no user registry became available within 10 seconds.   As a result, no application will start. Ensure that you have configured an appropriate user registry in the server.xml file.
```

After setting up user registry, I did not see this error again.

**Comment by gkwan-ibm** [comment]
close
- it is caused by an OL issue https://github.com/OpenLiberty/open-liberty/issues/1357
