### ISSUE TITLE
Minor issues: broken link and deprecated method usage

### ISSUE THREAD

**Issue by shin19991207** [OpenLiberty/guide-liberty-deep-dive#265]
- Link in the 'About' section in this repo is not working (leads to a blank page).
- The `getSystemCpuLoad()` method in [`finish/module-health-checks/src/main/java/io/openliberty/deepdive/rest/health/StartupCheck.java`](https://github.com/OpenLiberty/guide-liberty-deep-dive/blob/prod/finish/module-health-checks/src/main/java/io/openliberty/deepdive/rest/health/StartupCheck.java#L32) is deprecated - Use `getCpuLoad()` instead of this historically named method.

**Comment by gkwan-ibm** [comment]
closed
- fixed by PR #264
